rooms:
  - name: living_room
    type_device:
      - name_type: smart_light
        devices:
        - name: Đèn trần
          device_token: xdF2nW4aR9SAdqqPiym0
          device_id: fcceeaa0-3111-11f1-9981-cffbb69f5b14
          description_location: the ceiling of the living room
          shared_attributes:
            - name_key: led
              value: boolean
              description: Indicates whether the LED light is on or off

        - name: Đèn ngủ
          device_token: a1b2c3d4e5f6g7h8i9j0
          device_id: your-device-uuid-here
          description_location: the bedside table in the living room
          shared_attributes:
            - name_key: brightness
              value: integer
              description: Represents the brightness level of the night light (0-100)
            - name_key: led
              value: boolean
              description: Indicates whether the LED light is on or off
      
      - name_type: smart_fan
        devices:
          - name: quạt trần
            device_token: z9y8x7w6v5u4t3s2r1q0
            device_id: your-device-uuid-here
            description_location: the ceiling of the living room
            shared_attributes:
              - name_key: speed
                value: integer
                description: Represents the speed level of the fan (0-3)
              - name_key: toogle
                value: boolean
                description: Indicates whether the fan is on or off

      - name_type: smart_thermostat
        devices:
          - name: điều hòa
            device_token: m1n2o3p4q5r6s7t8u9v0
            device_id: your-device-uuid-here
            description_location: the wall of the living room
            shared_attributes:
              - name_key: temperature
                value: integer
                description: Represents the temperature setting of the thermostat (in degrees Celsius)
              - name_key: mode
                value: string
                description: Represents the mode of the thermostat (e.g., "cool", "heat", "auto")

  - name: kitchen
    type_device:
      - name_type: smart_fan
        devices:
          - name: quạt trần
            device_token: f9g8h7i6j5k4l3m2n1o0
            device_id: your-device-uuid-here
            type: smart_fan
            description_location: the ceiling of the kitchen
            shared_attributes:
              - name_key: speed
                value: integer
                description: Represents the speed level of the fan (0-3)
              - name_key: toogle
                value: boolean
                description: Indicates whether the fan is on or off

      - name_type: smart_light
        devices:
        - name: đèn bếp
          device_token: k1l2m3n4o5p6q7r8s9t0
          device_id: your-device-uuid-here
          type: smart_light
          description_location: the ceiling of the kitchen
          shared_attributes:
            - name_key: led
              value: boolean
              description: Indicates whether the LED light is on or off
